// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: build.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_BuildStatusPending BuildStatus = 0 //待执行
	BuildStatus_BuildStatusRunning BuildStatus = 1 //执行中
	BuildStatus_BuildStatusSuccess BuildStatus = 2 //执行成功
	BuildStatus_BuildStatusFailed  BuildStatus = 3 //执行失败
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BuildStatusPending",
		1: "BuildStatusRunning",
		2: "BuildStatusSuccess",
		3: "BuildStatusFailed",
	}
	BuildStatus_value = map[string]int32{
		"BuildStatusPending": 0,
		"BuildStatusRunning": 1,
		"BuildStatusSuccess": 2,
		"BuildStatusFailed":  3,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_build_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_build_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

type BuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId      uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId    uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId  uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PipelineId uint32 `protobuf:"varint,4,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Remark     string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Branch     string `protobuf:"bytes,6,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitId   string `protobuf:"bytes,7,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	HookId     int64  `protobuf:"varint,8,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
}

func (x *BuildReq) Reset() {
	*x = BuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReq) ProtoMessage() {}

func (x *BuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReq.ProtoReflect.Descriptor instead.
func (*BuildReq) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

func (x *BuildReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildReq) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildReq) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildReq) GetPipelineId() uint32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *BuildReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BuildReq) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildReq) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *BuildReq) GetHookId() int64 {
	if x != nil {
		return x.HookId
	}
	return 0
}

type BuildRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build *BuildRspInfo `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
}

func (x *BuildRsp) Reset() {
	*x = BuildRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRsp) ProtoMessage() {}

func (x *BuildRsp) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRsp.ProtoReflect.Descriptor instead.
func (*BuildRsp) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{1}
}

func (x *BuildRsp) GetBuild() *BuildRspInfo {
	if x != nil {
		return x.Build
	}
	return nil
}

// 构建响应信息
type BuildRspInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId           uint32          `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId         uint32          `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId       uint32          `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PipelineId      uint32          `protobuf:"varint,5,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Branch          string          `protobuf:"bytes,6,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitId        string          `protobuf:"bytes,7,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Pipeline        *PipelineSimple `protobuf:"bytes,8,opt,name=pipeline,proto3" json:"pipeline,omitempty"`                                      //流水线
	PipelinerunName string          `protobuf:"bytes,9,opt,name=pipelinerun_name,json=pipelinerunName,proto3" json:"pipelinerun_name,omitempty"` //构建生成的run_name
	Remark          string          `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	StartAt         int64           `protobuf:"varint,11,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt           int64           `protobuf:"varint,12,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Status          BuildStatus     `protobuf:"varint,13,opt,name=status,proto3,enum=protoc.BuildStatus" json:"status,omitempty"` // 状态：0-待执行；1-执行中；2-执行成功；3-执行失败
	HookId          int32           `protobuf:"varint,14,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	Creator         uint32          `protobuf:"varint,15,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatorInfo     *Creator        `protobuf:"bytes,16,opt,name=creator_info,json=creatorInfo,proto3" json:"creator_info,omitempty"`
}

func (x *BuildRspInfo) Reset() {
	*x = BuildRspInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRspInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRspInfo) ProtoMessage() {}

func (x *BuildRspInfo) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRspInfo.ProtoReflect.Descriptor instead.
func (*BuildRspInfo) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{2}
}

func (x *BuildRspInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildRspInfo) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildRspInfo) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildRspInfo) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildRspInfo) GetPipelineId() uint32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *BuildRspInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildRspInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *BuildRspInfo) GetPipeline() *PipelineSimple {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *BuildRspInfo) GetPipelinerunName() string {
	if x != nil {
		return x.PipelinerunName
	}
	return ""
}

func (x *BuildRspInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BuildRspInfo) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *BuildRspInfo) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *BuildRspInfo) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BuildStatusPending
}

func (x *BuildRspInfo) GetHookId() int32 {
	if x != nil {
		return x.HookId
	}
	return 0
}

func (x *BuildRspInfo) GetCreator() uint32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *BuildRspInfo) GetCreatorInfo() *Creator {
	if x != nil {
		return x.CreatorInfo
	}
	return nil
}

// 构建日志请求参数
type BuildLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId     uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId   uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BuildId   uint32 `protobuf:"varint,4,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *BuildLogReq) Reset() {
	*x = BuildLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogReq) ProtoMessage() {}

func (x *BuildLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogReq.ProtoReflect.Descriptor instead.
func (*BuildLogReq) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildLogReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildLogReq) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildLogReq) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildLogReq) GetBuildId() uint32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type BuildLogRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buildlog *BuildLogRspInfo `protobuf:"bytes,1,opt,name=buildlog,proto3" json:"buildlog,omitempty"`
}

func (x *BuildLogRsp) Reset() {
	*x = BuildLogRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogRsp) ProtoMessage() {}

func (x *BuildLogRsp) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogRsp.ProtoReflect.Descriptor instead.
func (*BuildLogRsp) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{4}
}

func (x *BuildLogRsp) GetBuildlog() *BuildLogRspInfo {
	if x != nil {
		return x.Buildlog
	}
	return nil
}

// log返回值
type BuildLogRspInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Branch   string      `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitId string      `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	StartAt  int64       `protobuf:"varint,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt    int64       `protobuf:"varint,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Status   BuildStatus `protobuf:"varint,6,opt,name=status,proto3,enum=protoc.BuildStatus" json:"status,omitempty"`
	Error    string      `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ImageId  string      `protobuf:"bytes,8,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Content  string      `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Timeline string      `protobuf:"bytes,10,opt,name=timeline,proto3" json:"timeline,omitempty"`
}

func (x *BuildLogRspInfo) Reset() {
	*x = BuildLogRspInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildLogRspInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogRspInfo) ProtoMessage() {}

func (x *BuildLogRspInfo) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogRspInfo.ProtoReflect.Descriptor instead.
func (*BuildLogRspInfo) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{5}
}

func (x *BuildLogRspInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildLogRspInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildLogRspInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *BuildLogRspInfo) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *BuildLogRspInfo) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *BuildLogRspInfo) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BuildStatusPending
}

func (x *BuildLogRspInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildLogRspInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *BuildLogRspInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BuildLogRspInfo) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

// 获取构建列表请求
type BuildListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId      uint32      `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId    uint32      `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId  uint32      `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PipelineId uint32      `protobuf:"varint,4,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status     BuildStatus `protobuf:"varint,5,opt,name=status,proto3,enum=protoc.BuildStatus" json:"status,omitempty"`
	HookId     uint32      `protobuf:"varint,6,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	Page       uint32      `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	Pagesize   uint32      `protobuf:"varint,8,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
}

func (x *BuildListReq) Reset() {
	*x = BuildListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildListReq) ProtoMessage() {}

func (x *BuildListReq) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildListReq.ProtoReflect.Descriptor instead.
func (*BuildListReq) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{6}
}

func (x *BuildListReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildListReq) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildListReq) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildListReq) GetPipelineId() uint32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *BuildListReq) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BuildStatusPending
}

func (x *BuildListReq) GetHookId() uint32 {
	if x != nil {
		return x.HookId
	}
	return 0
}

func (x *BuildListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BuildListReq) GetPagesize() uint32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

// 构建列表响应信息
type BuildListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32           `protobuf:"zigzag32,1,opt,name=page,proto3" json:"page,omitempty"`
	Pagesize int32           `protobuf:"zigzag32,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	Total    int32           `protobuf:"zigzag32,3,opt,name=total,proto3" json:"total,omitempty"`
	Data     []*BuildRspInfo `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BuildListRsp) Reset() {
	*x = BuildListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildListRsp) ProtoMessage() {}

func (x *BuildListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildListRsp.ProtoReflect.Descriptor instead.
func (*BuildListRsp) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{7}
}

func (x *BuildListRsp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BuildListRsp) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *BuildListRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BuildListRsp) GetData() []*BuildRspInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 重新构建请求
type BuildReReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId     uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId   uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BuildId   uint32 `protobuf:"varint,4,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *BuildReReq) Reset() {
	*x = BuildReReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildReReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReReq) ProtoMessage() {}

func (x *BuildReReq) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReReq.ProtoReflect.Descriptor instead.
func (*BuildReReq) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{8}
}

func (x *BuildReReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildReReq) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildReReq) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildReReq) GetBuildId() uint32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

type BuildFastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId          uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId        uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId      uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PipelineHookId uint32 `protobuf:"varint,4,opt,name=pipeline_hook_id,json=pipelineHookId,proto3" json:"pipeline_hook_id,omitempty"`
}

func (x *BuildFastReq) Reset() {
	*x = BuildFastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildFastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFastReq) ProtoMessage() {}

func (x *BuildFastReq) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFastReq.ProtoReflect.Descriptor instead.
func (*BuildFastReq) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{9}
}

func (x *BuildFastReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BuildFastReq) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BuildFastReq) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *BuildFastReq) GetPipelineHookId() uint32 {
	if x != nil {
		return x.PipelineHookId
	}
	return 0
}

type BuildFastRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fastbuild *BuildFast `protobuf:"bytes,1,opt,name=fastbuild,proto3" json:"fastbuild,omitempty"`
}

func (x *BuildFastRsp) Reset() {
	*x = BuildFastRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildFastRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFastRsp) ProtoMessage() {}

func (x *BuildFastRsp) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFastRsp.ProtoReflect.Descriptor instead.
func (*BuildFastRsp) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{10}
}

func (x *BuildFastRsp) GetFastbuild() *BuildFast {
	if x != nil {
		return x.Fastbuild
	}
	return nil
}

type BuildFast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch     string          `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitId   string          `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	PipelineId uint32          `protobuf:"varint,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Pipeline   *PipelineSimple `protobuf:"bytes,4,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Remark     string          `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *BuildFast) Reset() {
	*x = BuildFast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_build_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildFast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFast) ProtoMessage() {}

func (x *BuildFast) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFast.ProtoReflect.Descriptor instead.
func (*BuildFast) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{11}
}

func (x *BuildFast) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildFast) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *BuildFast) GetPipelineId() uint32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *BuildFast) GetPipeline() *PipelineSimple {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *BuildFast) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_build_proto protoreflect.FileDescriptor

var file_build_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x68, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x08, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x73, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x22, 0x82, 0x04, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x73, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x75, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x72, 0x75, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x79, 0x0a, 0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x22, 0x42, 0x0a, 0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x73, 0x70,
	0x12, 0x33, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x4c, 0x6f, 0x67, 0x52, 0x73, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x6c, 0x6f, 0x67, 0x22, 0x9c, 0x02, 0x0a, 0x0f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c,
	0x6f, 0x67, 0x52, 0x73, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0xf6, 0x01, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x7e, 0x0a,
	0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x11, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x73, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x78, 0x0a,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x46, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x6f, 0x6f,
	0x6b, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x61, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x09, 0x66, 0x61, 0x73, 0x74, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x61, 0x73, 0x74, 0x52, 0x09, 0x66, 0x61, 0x73, 0x74, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x22, 0xad, 0x01, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x61,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x2a, 0x6c, 0x0a, 0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x03, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_build_proto_rawDescOnce sync.Once
	file_build_proto_rawDescData = file_build_proto_rawDesc
)

func file_build_proto_rawDescGZIP() []byte {
	file_build_proto_rawDescOnce.Do(func() {
		file_build_proto_rawDescData = protoimpl.X.CompressGZIP(file_build_proto_rawDescData)
	})
	return file_build_proto_rawDescData
}

var file_build_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_build_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_build_proto_goTypes = []interface{}{
	(BuildStatus)(0),        // 0: protoc.BuildStatus
	(*BuildReq)(nil),        // 1: protoc.BuildReq
	(*BuildRsp)(nil),        // 2: protoc.BuildRsp
	(*BuildRspInfo)(nil),    // 3: protoc.BuildRspInfo
	(*BuildLogReq)(nil),     // 4: protoc.BuildLogReq
	(*BuildLogRsp)(nil),     // 5: protoc.BuildLogRsp
	(*BuildLogRspInfo)(nil), // 6: protoc.BuildLogRspInfo
	(*BuildListReq)(nil),    // 7: protoc.BuildListReq
	(*BuildListRsp)(nil),    // 8: protoc.BuildListRsp
	(*BuildReReq)(nil),      // 9: protoc.BuildReReq
	(*BuildFastReq)(nil),    // 10: protoc.BuildFastReq
	(*BuildFastRsp)(nil),    // 11: protoc.BuildFastRsp
	(*BuildFast)(nil),       // 12: protoc.BuildFast
	(*PipelineSimple)(nil),  // 13: protoc.PipelineSimple
	(*Creator)(nil),         // 14: protoc.Creator
}
var file_build_proto_depIdxs = []int32{
	3,  // 0: protoc.BuildRsp.build:type_name -> protoc.BuildRspInfo
	13, // 1: protoc.BuildRspInfo.pipeline:type_name -> protoc.PipelineSimple
	0,  // 2: protoc.BuildRspInfo.status:type_name -> protoc.BuildStatus
	14, // 3: protoc.BuildRspInfo.creator_info:type_name -> protoc.Creator
	6,  // 4: protoc.BuildLogRsp.buildlog:type_name -> protoc.BuildLogRspInfo
	0,  // 5: protoc.BuildLogRspInfo.status:type_name -> protoc.BuildStatus
	0,  // 6: protoc.BuildListReq.status:type_name -> protoc.BuildStatus
	3,  // 7: protoc.BuildListRsp.data:type_name -> protoc.BuildRspInfo
	12, // 8: protoc.BuildFastRsp.fastbuild:type_name -> protoc.BuildFast
	13, // 9: protoc.BuildFast.pipeline:type_name -> protoc.PipelineSimple
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_build_proto_init() }
func file_build_proto_init() {
	if File_build_proto != nil {
		return
	}
	file_pipeline_proto_init()
	file_creator_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_build_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRspInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildLogRspInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildReReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildFastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildFastRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_build_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildFast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_build_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_build_proto_goTypes,
		DependencyIndexes: file_build_proto_depIdxs,
		EnumInfos:         file_build_proto_enumTypes,
		MessageInfos:      file_build_proto_msgTypes,
	}.Build()
	File_build_proto = out.File
	file_build_proto_rawDesc = nil
	file_build_proto_goTypes = nil
	file_build_proto_depIdxs = nil
}
