// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: env.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvType int32

const (
	EnvType_EnvNotDef EnvType = 0 // 未定义
	EnvType_EnvDev    EnvType = 1 // 开发环境
	EnvType_EnvTest   EnvType = 2 // 测试环境
	EnvType_EnvPre    EnvType = 3 // 预发布环境
	EnvType_EnvPro    EnvType = 4 // 正式环境
)

// Enum value maps for EnvType.
var (
	EnvType_name = map[int32]string{
		0: "EnvNotDef",
		1: "EnvDev",
		2: "EnvTest",
		3: "EnvPre",
		4: "EnvPro",
	}
	EnvType_value = map[string]int32{
		"EnvNotDef": 0,
		"EnvDev":    1,
		"EnvTest":   2,
		"EnvPre":    3,
		"EnvPro":    4,
	}
)

func (x EnvType) Enum() *EnvType {
	p := new(EnvType)
	*p = x
	return p
}

func (x EnvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvType) Descriptor() protoreflect.EnumDescriptor {
	return file_env_proto_enumTypes[0].Descriptor()
}

func (EnvType) Type() protoreflect.EnumType {
	return &file_env_proto_enumTypes[0]
}

func (x EnvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvType.Descriptor instead.
func (EnvType) EnumDescriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{0}
}

type EnvList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envs []*Env `protobuf:"bytes,1,rep,name=envs,proto3" json:"envs,omitempty"`
}

func (x *EnvList) Reset() {
	*x = EnvList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvList) ProtoMessage() {}

func (x *EnvList) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvList.ProtoReflect.Descriptor instead.
func (*EnvList) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{0}
}

func (x *EnvList) GetEnvs() []*Env {
	if x != nil {
		return x.Envs
	}
	return nil
}

type Env struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  EnvType `protobuf:"varint,2,opt,name=type,proto3,enum=protoc.EnvType" json:"type,omitempty"`
	Title string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Env) Reset() {
	*x = Env{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Env) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Env) ProtoMessage() {}

func (x *Env) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Env.ProtoReflect.Descriptor instead.
func (*Env) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{1}
}

func (x *Env) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Env) GetType() EnvType {
	if x != nil {
		return x.Type
	}
	return EnvType_EnvNotDef
}

func (x *Env) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_env_proto protoreflect.FileDescriptor

var file_env_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x22, 0x2a, 0x0a, 0x07, 0x45, 0x6e, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x45, 0x6e, 0x76, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x22,
	0x50, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x45, 0x6e,
	0x76, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x2a, 0x49, 0x0a, 0x07, 0x45, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x6e, 0x76, 0x4e, 0x6f, 0x74, 0x44, 0x65, 0x66, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45,
	0x6e, 0x76, 0x44, 0x65, 0x76, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x6e, 0x76, 0x54, 0x65,
	0x73, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x6e, 0x76, 0x50, 0x72, 0x65, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x45, 0x6e, 0x76, 0x50, 0x72, 0x6f, 0x10, 0x04, 0x42, 0x10, 0x5a, 0x0e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_env_proto_rawDescOnce sync.Once
	file_env_proto_rawDescData = file_env_proto_rawDesc
)

func file_env_proto_rawDescGZIP() []byte {
	file_env_proto_rawDescOnce.Do(func() {
		file_env_proto_rawDescData = protoimpl.X.CompressGZIP(file_env_proto_rawDescData)
	})
	return file_env_proto_rawDescData
}

var file_env_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_env_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_env_proto_goTypes = []interface{}{
	(EnvType)(0),    // 0: protoc.EnvType
	(*EnvList)(nil), // 1: protoc.EnvList
	(*Env)(nil),     // 2: protoc.Env
}
var file_env_proto_depIdxs = []int32{
	2, // 0: protoc.EnvList.envs:type_name -> protoc.Env
	0, // 1: protoc.Env.type:type_name -> protoc.EnvType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_env_proto_init() }
func file_env_proto_init() {
	if File_env_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_env_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Env); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_env_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_env_proto_goTypes,
		DependencyIndexes: file_env_proto_depIdxs,
		EnumInfos:         file_env_proto_enumTypes,
		MessageInfos:      file_env_proto_msgTypes,
	}.Build()
	File_env_proto = out.File
	file_env_proto_rawDesc = nil
	file_env_proto_goTypes = nil
	file_env_proto_depIdxs = nil
}
