// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: https.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Https struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable     *uint32 `protobuf:"varint,1,req,name=enable" json:"enable,omitempty"`
	CertId     *uint32 `protobuf:"varint,2,req,name=cert_id,json=certId" json:"cert_id,omitempty"`
	Http2      *uint32 `protobuf:"varint,3,req,name=http2" json:"http2,omitempty"`
	ForceHttps *uint32 `protobuf:"varint,4,req,name=force_https,json=forceHttps" json:"force_https,omitempty"`
}

func (x *Https) Reset() {
	*x = Https{}
	if protoimpl.UnsafeEnabled {
		mi := &file_https_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Https) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Https) ProtoMessage() {}

func (x *Https) ProtoReflect() protoreflect.Message {
	mi := &file_https_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Https.ProtoReflect.Descriptor instead.
func (*Https) Descriptor() ([]byte, []int) {
	return file_https_proto_rawDescGZIP(), []int{0}
}

func (x *Https) GetEnable() uint32 {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return 0
}

func (x *Https) GetCertId() uint32 {
	if x != nil && x.CertId != nil {
		return *x.CertId
	}
	return 0
}

func (x *Https) GetHttp2() uint32 {
	if x != nil && x.Http2 != nil {
		return *x.Http2
	}
	return 0
}

func (x *Https) GetForceHttps() uint32 {
	if x != nil && x.ForceHttps != nil {
		return *x.ForceHttps
	}
	return 0
}

var File_https_proto protoreflect.FileDescriptor

var file_https_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x6f, 0x0a, 0x05, 0x48, 0x74, 0x74, 0x70, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x68, 0x74, 0x74, 0x70, 0x32, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05,
	0x68, 0x74, 0x74, 0x70, 0x32, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x68,
	0x74, 0x74, 0x70, 0x73, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x48, 0x74, 0x74, 0x70, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
}

var (
	file_https_proto_rawDescOnce sync.Once
	file_https_proto_rawDescData = file_https_proto_rawDesc
)

func file_https_proto_rawDescGZIP() []byte {
	file_https_proto_rawDescOnce.Do(func() {
		file_https_proto_rawDescData = protoimpl.X.CompressGZIP(file_https_proto_rawDescData)
	})
	return file_https_proto_rawDescData
}

var file_https_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_https_proto_goTypes = []interface{}{
	(*Https)(nil), // 0: protoc.Https
}
var file_https_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_https_proto_init() }
func file_https_proto_init() {
	if File_https_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_https_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Https); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_https_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_https_proto_goTypes,
		DependencyIndexes: file_https_proto_depIdxs,
		MessageInfos:      file_https_proto_msgTypes,
	}.Build()
	File_https_proto = out.File
	file_https_proto_rawDesc = nil
	file_https_proto_goTypes = nil
	file_https_proto_depIdxs = nil
}
