// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: organization.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgROLE int32

const (
	OrgROLE_ROLE_Normal   OrgROLE = 0
	OrgROLE_ROLE_MANAGER  OrgROLE = 1 //管理员
	OrgROLE_ROLE_PM       OrgROLE = 2 //产品经理
	OrgROLE_ROLE_DEV      OrgROLE = 3 //研发
	OrgROLE_ROLE_TESTER   OrgROLE = 4 //测试
	OrgROLE_ROLE_OPS      OrgROLE = 5 //运维
	OrgROLE_ROLE_DIRECTOR OrgROLE = 9 //负责人
)

// Enum value maps for OrgROLE.
var (
	OrgROLE_name = map[int32]string{
		0: "ROLE_Normal",
		1: "ROLE_MANAGER",
		2: "ROLE_PM",
		3: "ROLE_DEV",
		4: "ROLE_TESTER",
		5: "ROLE_OPS",
		9: "ROLE_DIRECTOR",
	}
	OrgROLE_value = map[string]int32{
		"ROLE_Normal":   0,
		"ROLE_MANAGER":  1,
		"ROLE_PM":       2,
		"ROLE_DEV":      3,
		"ROLE_TESTER":   4,
		"ROLE_OPS":      5,
		"ROLE_DIRECTOR": 9,
	}
)

func (x OrgROLE) Enum() *OrgROLE {
	p := new(OrgROLE)
	*p = x
	return p
}

func (x OrgROLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgROLE) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[0].Descriptor()
}

func (OrgROLE) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[0]
}

func (x OrgROLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgROLE.Descriptor instead.
func (OrgROLE) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

type OrgAUTH int32

const (
	OrgAUTH_AUTH_NO       OrgAUTH = 0 //未认证
	OrgAUTH_AUTH_COMPANY  OrgAUTH = 1 //企业认证
	OrgAUTH_AUTH_PERSONAL OrgAUTH = 2 //个人认证
)

// Enum value maps for OrgAUTH.
var (
	OrgAUTH_name = map[int32]string{
		0: "AUTH_NO",
		1: "AUTH_COMPANY",
		2: "AUTH_PERSONAL",
	}
	OrgAUTH_value = map[string]int32{
		"AUTH_NO":       0,
		"AUTH_COMPANY":  1,
		"AUTH_PERSONAL": 2,
	}
)

func (x OrgAUTH) Enum() *OrgAUTH {
	p := new(OrgAUTH)
	*p = x
	return p
}

func (x OrgAUTH) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgAUTH) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[1].Descriptor()
}

func (OrgAUTH) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[1]
}

func (x OrgAUTH) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgAUTH.Descriptor instead.
func (OrgAUTH) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

type OrgTYPE int32

const (
	OrgTYPE_TYPE_PERSONAL OrgTYPE = 0 //个人
	OrgTYPE_TYPE_COMPANY  OrgTYPE = 1 //公司
)

// Enum value maps for OrgTYPE.
var (
	OrgTYPE_name = map[int32]string{
		0: "TYPE_PERSONAL",
		1: "TYPE_COMPANY",
	}
	OrgTYPE_value = map[string]int32{
		"TYPE_PERSONAL": 0,
		"TYPE_COMPANY":  1,
	}
)

func (x OrgTYPE) Enum() *OrgTYPE {
	p := new(OrgTYPE)
	*p = x
	return p
}

func (x OrgTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[2].Descriptor()
}

func (OrgTYPE) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[2]
}

func (x OrgTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgTYPE.Descriptor instead.
func (OrgTYPE) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

type OrgSTATUS int32

const (
	OrgSTATUS_STATUS_IN_DISSOLUTION OrgSTATUS = 0 //解散中
	OrgSTATUS_STATUS_NORMAL         OrgSTATUS = 1 //正常
)

// Enum value maps for OrgSTATUS.
var (
	OrgSTATUS_name = map[int32]string{
		0: "STATUS_IN_DISSOLUTION",
		1: "STATUS_NORMAL",
	}
	OrgSTATUS_value = map[string]int32{
		"STATUS_IN_DISSOLUTION": 0,
		"STATUS_NORMAL":         1,
	}
)

func (x OrgSTATUS) Enum() *OrgSTATUS {
	p := new(OrgSTATUS)
	*p = x
	return p
}

func (x OrgSTATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrgSTATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[3].Descriptor()
}

func (OrgSTATUS) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[3]
}

func (x OrgSTATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrgSTATUS.Descriptor instead.
func (OrgSTATUS) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

type Orgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orgs []*Organization `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
}

func (x *Orgs) Reset() {
	*x = Orgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orgs) ProtoMessage() {}

func (x *Orgs) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orgs.ProtoReflect.Descriptor instead.
func (*Orgs) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Orgs) GetOrgs() []*Organization {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type Organization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // 组织id
	Type    uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                      // 类型：0-个人；1-公司
	TypeS   string `protobuf:"bytes,3,opt,name=type_s,json=typeS,proto3" json:"type_s,omitempty"`        // 类型中文
	Title   string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                     // 组织名称
	Alias   string `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`                     // 组织标识
	Logo    string `protobuf:"bytes,6,opt,name=logo,proto3" json:"logo,omitempty"`                       // LOGO
	Desc    string `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`                       // 组织描述
	Role    uint32 `protobuf:"varint,8,opt,name=role,proto3" json:"role,omitempty"`                      // 角色
	RoleS   string `protobuf:"bytes,9,opt,name=role_s,json=roleS,proto3" json:"role_s,omitempty"`        // 角色中文
	Status  uint32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                 // 状态
	StatusS string `protobuf:"bytes,11,opt,name=status_s,json=statusS,proto3" json:"status_s,omitempty"` // 状态中文
}

func (x *Organization) Reset() {
	*x = Organization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Organization) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Organization) GetTypeS() string {
	if x != nil {
		return x.TypeS
	}
	return ""
}

func (x *Organization) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Organization) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Organization) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Organization) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Organization) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Organization) GetRoleS() string {
	if x != nil {
		return x.RoleS
	}
	return ""
}

func (x *Organization) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Organization) GetStatusS() string {
	if x != nil {
		return x.StatusS
	}
	return ""
}

type OrgProfileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Org *OrgProfile `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *OrgProfileRsp) Reset() {
	*x = OrgProfileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgProfileRsp) ProtoMessage() {}

func (x *OrgProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgProfileRsp.ProtoReflect.Descriptor instead.
func (*OrgProfileRsp) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

func (x *OrgProfileRsp) GetOrg() *OrgProfile {
	if x != nil {
		return x.Org
	}
	return nil
}

// 组织详情
type OrgProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 组织id
	IdAuth      OrgAUTH   `protobuf:"varint,2,opt,name=id_auth,json=idAuth,proto3,enum=protoc.OrgAUTH" json:"id_auth,omitempty"`
	Title       string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type        OrgTYPE   `protobuf:"varint,4,opt,name=type,proto3,enum=protoc.OrgTYPE" json:"type,omitempty"`
	Status      OrgSTATUS `protobuf:"varint,5,opt,name=status,proto3,enum=protoc.OrgSTATUS" json:"status,omitempty"`
	Role        OrgROLE   `protobuf:"varint,6,opt,name=role,proto3,enum=protoc.OrgROLE" json:"role,omitempty"`
	Logo        string    `protobuf:"bytes,7,opt,name=logo,proto3" json:"logo,omitempty"`
	IsAdminOrg  bool      `protobuf:"varint,8,opt,name=is_admin_org,json=isAdminOrg,proto3" json:"is_admin_org,omitempty"` // 是否是组织所有者
	Desc        string    `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	Creator     uint32    `protobuf:"varint,10,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatorInfo *Creator  `protobuf:"bytes,11,opt,name=creator_info,json=creatorInfo,proto3" json:"creator_info,omitempty"`
	CreatedAt   int64     `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *OrgProfile) Reset() {
	*x = OrgProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgProfile) ProtoMessage() {}

func (x *OrgProfile) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgProfile.ProtoReflect.Descriptor instead.
func (*OrgProfile) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

func (x *OrgProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrgProfile) GetIdAuth() OrgAUTH {
	if x != nil {
		return x.IdAuth
	}
	return OrgAUTH_AUTH_NO
}

func (x *OrgProfile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrgProfile) GetType() OrgTYPE {
	if x != nil {
		return x.Type
	}
	return OrgTYPE_TYPE_PERSONAL
}

func (x *OrgProfile) GetStatus() OrgSTATUS {
	if x != nil {
		return x.Status
	}
	return OrgSTATUS_STATUS_IN_DISSOLUTION
}

func (x *OrgProfile) GetRole() OrgROLE {
	if x != nil {
		return x.Role
	}
	return OrgROLE_ROLE_Normal
}

func (x *OrgProfile) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *OrgProfile) GetIsAdminOrg() bool {
	if x != nil {
		return x.IsAdminOrg
	}
	return false
}

func (x *OrgProfile) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *OrgProfile) GetCreator() uint32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *OrgProfile) GetCreatorInfo() *Creator {
	if x != nil {
		return x.CreatorInfo
	}
	return nil
}

func (x *OrgProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_organization_proto protoreflect.FileDescriptor

var file_organization_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x0d, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x04, 0x4f,
	0x72, 0x67, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x6f, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6f, 0x72, 0x67, 0x73, 0x22, 0xfb, 0x01,
	0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x73, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x22, 0x35, 0x0a, 0x0d, 0x4f,
	0x72, 0x67, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x03,
	0x6f, 0x72, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2e, 0x4f, 0x72, 0x67, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x03, 0x6f,
	0x72, 0x67, 0x22, 0x88, 0x03, 0x0a, 0x0a, 0x4f, 0x72, 0x67, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x28, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x4f, 0x72, 0x67, 0x41,
	0x55, 0x54, 0x48, 0x52, 0x06, 0x69, 0x64, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x4f, 0x72, 0x67, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x4f, 0x72, 0x67, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x4f, 0x4c, 0x45,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x73,
	0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6f, 0x72, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4f, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x79, 0x0a,
	0x07, 0x4f, 0x72, 0x67, 0x52, 0x4f, 0x4c, 0x45, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4c,
	0x45, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x4f, 0x4c, 0x45, 0x5f, 0x50, 0x4d, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x44, 0x45, 0x56, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54,
	0x45, 0x53, 0x54, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x4f, 0x50, 0x53, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x09, 0x2a, 0x3b, 0x0a, 0x07, 0x4f, 0x72, 0x67, 0x41,
	0x55, 0x54, 0x48, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x4e, 0x4f, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x59,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f,
	0x4e, 0x41, 0x4c, 0x10, 0x02, 0x2a, 0x2e, 0x0a, 0x07, 0x4f, 0x72, 0x67, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x41, 0x4e, 0x59, 0x10, 0x01, 0x2a, 0x39, 0x0a, 0x09, 0x4f, 0x72, 0x67, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x5f,
	0x44, 0x49, 0x53, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01,
	0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData = file_organization_proto_rawDesc
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(file_organization_proto_rawDescData)
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_organization_proto_goTypes = []interface{}{
	(OrgROLE)(0),          // 0: protoc.OrgROLE
	(OrgAUTH)(0),          // 1: protoc.OrgAUTH
	(OrgTYPE)(0),          // 2: protoc.OrgTYPE
	(OrgSTATUS)(0),        // 3: protoc.OrgSTATUS
	(*Orgs)(nil),          // 4: protoc.Orgs
	(*Organization)(nil),  // 5: protoc.Organization
	(*OrgProfileRsp)(nil), // 6: protoc.OrgProfileRsp
	(*OrgProfile)(nil),    // 7: protoc.OrgProfile
	(*Creator)(nil),       // 8: protoc.Creator
}
var file_organization_proto_depIdxs = []int32{
	5, // 0: protoc.Orgs.orgs:type_name -> protoc.Organization
	7, // 1: protoc.OrgProfileRsp.org:type_name -> protoc.OrgProfile
	1, // 2: protoc.OrgProfile.id_auth:type_name -> protoc.OrgAUTH
	2, // 3: protoc.OrgProfile.type:type_name -> protoc.OrgTYPE
	3, // 4: protoc.OrgProfile.status:type_name -> protoc.OrgSTATUS
	0, // 5: protoc.OrgProfile.role:type_name -> protoc.OrgROLE
	8, // 6: protoc.OrgProfile.creator_info:type_name -> protoc.Creator
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	file_creator_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_organization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Organization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgProfileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_organization_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		EnumInfos:         file_organization_proto_enumTypes,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_rawDesc = nil
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
