// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: podprofile.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodProfileReloadRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId     uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId   uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PodId     uint32 `protobuf:"varint,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	ForcePull bool   `protobuf:"varint,5,opt,name=force_pull,json=forcePull,proto3" json:"force_pull,omitempty"`
}

func (x *PodProfileReloadRsp) Reset() {
	*x = PodProfileReloadRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podprofile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodProfileReloadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodProfileReloadRsp) ProtoMessage() {}

func (x *PodProfileReloadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_podprofile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodProfileReloadRsp.ProtoReflect.Descriptor instead.
func (*PodProfileReloadRsp) Descriptor() ([]byte, []int) {
	return file_podprofile_proto_rawDescGZIP(), []int{0}
}

func (x *PodProfileReloadRsp) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *PodProfileReloadRsp) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PodProfileReloadRsp) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PodProfileReloadRsp) GetPodId() uint32 {
	if x != nil {
		return x.PodId
	}
	return 0
}

func (x *PodProfileReloadRsp) GetForcePull() bool {
	if x != nil {
		return x.ForcePull
	}
	return false
}

type PodProfileScaleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId     uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId   uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProjectId uint32 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PodId     uint32 `protobuf:"varint,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Replicas  uint32 `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *PodProfileScaleRsp) Reset() {
	*x = PodProfileScaleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podprofile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodProfileScaleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodProfileScaleRsp) ProtoMessage() {}

func (x *PodProfileScaleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_podprofile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodProfileScaleRsp.ProtoReflect.Descriptor instead.
func (*PodProfileScaleRsp) Descriptor() ([]byte, []int) {
	return file_podprofile_proto_rawDescGZIP(), []int{1}
}

func (x *PodProfileScaleRsp) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *PodProfileScaleRsp) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *PodProfileScaleRsp) GetProjectId() uint32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PodProfileScaleRsp) GetPodId() uint32 {
	if x != nil {
		return x.PodId
	}
	return 0
}

func (x *PodProfileScaleRsp) GetReplicas() uint32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

var File_podprofile_proto protoreflect.FileDescriptor

var file_podprofile_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6f, 0x64, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x9c, 0x01, 0x0a, 0x13, 0x50,
	0x6f, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x22, 0x98, 0x01, 0x0a, 0x12, 0x50, 0x6f,
	0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_podprofile_proto_rawDescOnce sync.Once
	file_podprofile_proto_rawDescData = file_podprofile_proto_rawDesc
)

func file_podprofile_proto_rawDescGZIP() []byte {
	file_podprofile_proto_rawDescOnce.Do(func() {
		file_podprofile_proto_rawDescData = protoimpl.X.CompressGZIP(file_podprofile_proto_rawDescData)
	})
	return file_podprofile_proto_rawDescData
}

var file_podprofile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podprofile_proto_goTypes = []interface{}{
	(*PodProfileReloadRsp)(nil), // 0: protoc.PodProfileReloadRsp
	(*PodProfileScaleRsp)(nil),  // 1: protoc.PodProfileScaleRsp
}
var file_podprofile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podprofile_proto_init() }
func file_podprofile_proto_init() {
	if File_podprofile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podprofile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodProfileReloadRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podprofile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodProfileScaleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podprofile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_podprofile_proto_goTypes,
		DependencyIndexes: file_podprofile_proto_depIdxs,
		MessageInfos:      file_podprofile_proto_msgTypes,
	}.Build()
	File_podprofile_proto = out.File
	file_podprofile_proto_rawDesc = nil
	file_podprofile_proto_goTypes = nil
	file_podprofile_proto_depIdxs = nil
}
