// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: ssl.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSLSimpleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId   uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Domain  string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *SSLSimpleListReq) Reset() {
	*x = SSLSimpleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLSimpleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLSimpleListReq) ProtoMessage() {}

func (x *SSLSimpleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLSimpleListReq.ProtoReflect.Descriptor instead.
func (*SSLSimpleListReq) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{0}
}

func (x *SSLSimpleListReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLSimpleListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SSLSimpleListReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type SSLSimpleListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certs []*SSLSimpleList `protobuf:"bytes,1,rep,name=certs,proto3" json:"certs,omitempty"`
}

func (x *SSLSimpleListRsp) Reset() {
	*x = SSLSimpleListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLSimpleListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLSimpleListRsp) ProtoMessage() {}

func (x *SSLSimpleListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLSimpleListRsp.ProtoReflect.Descriptor instead.
func (*SSLSimpleListRsp) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{1}
}

func (x *SSLSimpleListRsp) GetCerts() []*SSLSimpleList {
	if x != nil {
		return x.Certs
	}
	return nil
}

type SSLSimpleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *SSLSimpleList) Reset() {
	*x = SSLSimpleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLSimpleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLSimpleList) ProtoMessage() {}

func (x *SSLSimpleList) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLSimpleList.ProtoReflect.Descriptor instead.
func (*SSLSimpleList) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{2}
}

func (x *SSLSimpleList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSLSimpleList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SSLCertCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId   uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Pubkey  string `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Privkey string `protobuf:"bytes,4,opt,name=privkey,proto3" json:"privkey,omitempty"`
}

func (x *SSLCertCreateReq) Reset() {
	*x = SSLCertCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertCreateReq) ProtoMessage() {}

func (x *SSLCertCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertCreateReq.ProtoReflect.Descriptor instead.
func (*SSLCertCreateReq) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{3}
}

func (x *SSLCertCreateReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SSLCertCreateReq) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *SSLCertCreateReq) GetPrivkey() string {
	if x != nil {
		return x.Privkey
	}
	return ""
}

type SSLCertCreateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert *SSLCertCreate `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *SSLCertCreateRsp) Reset() {
	*x = SSLCertCreateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertCreateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertCreateRsp) ProtoMessage() {}

func (x *SSLCertCreateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertCreateRsp.ProtoReflect.Descriptor instead.
func (*SSLCertCreateRsp) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{4}
}

func (x *SSLCertCreateRsp) GetCert() *SSLCertCreate {
	if x != nil {
		return x.Cert
	}
	return nil
}

type SSLCertCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId       uint32              `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Title       string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Pubkey      string              `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Privkey     string              `protobuf:"bytes,5,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Attrs       *SSLCertCreateAttrs `protobuf:"bytes,6,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Creator     uint32              `protobuf:"varint,7,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt   int64               `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatorInfo *Creator            `protobuf:"bytes,9,opt,name=creatorInfo,proto3" json:"creatorInfo,omitempty"`
}

func (x *SSLCertCreate) Reset() {
	*x = SSLCertCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertCreate) ProtoMessage() {}

func (x *SSLCertCreate) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertCreate.ProtoReflect.Descriptor instead.
func (*SSLCertCreate) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{5}
}

func (x *SSLCertCreate) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSLCertCreate) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SSLCertCreate) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *SSLCertCreate) GetPrivkey() string {
	if x != nil {
		return x.Privkey
	}
	return ""
}

func (x *SSLCertCreate) GetAttrs() *SSLCertCreateAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *SSLCertCreate) GetCreator() uint32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *SSLCertCreate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SSLCertCreate) GetCreatorInfo() *Creator {
	if x != nil {
		return x.CreatorInfo
	}
	return nil
}

// {"domain":"wiki.swoole.com","issuer":"Encryption Everywhere DV TLS CA - G1","sign":"RSA-SHA256","issue_at":1636934400,"expired_at":1668556799,"fingerprint":"06BAF40E0AB269D6EA72E8559EA856AC2C497202"}
type SSLCertCreateAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain      string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Issuer      string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Sign        string `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	IssueAt     int64  `protobuf:"varint,5,opt,name=issue_at,json=issueAt,proto3" json:"issue_at,omitempty"`
	ExpiredAt   int64  `protobuf:"varint,6,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	Fingerprint string `protobuf:"bytes,7,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (x *SSLCertCreateAttrs) Reset() {
	*x = SSLCertCreateAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertCreateAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertCreateAttrs) ProtoMessage() {}

func (x *SSLCertCreateAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertCreateAttrs.ProtoReflect.Descriptor instead.
func (*SSLCertCreateAttrs) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{6}
}

func (x *SSLCertCreateAttrs) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SSLCertCreateAttrs) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *SSLCertCreateAttrs) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *SSLCertCreateAttrs) GetIssueAt() int64 {
	if x != nil {
		return x.IssueAt
	}
	return 0
}

func (x *SSLCertCreateAttrs) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *SSLCertCreateAttrs) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type SSLCertListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId    uint32 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Keyword  string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Page     uint32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Pagesize uint32 `protobuf:"varint,5,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
}

func (x *SSLCertListReq) Reset() {
	*x = SSLCertListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertListReq) ProtoMessage() {}

func (x *SSLCertListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertListReq.ProtoReflect.Descriptor instead.
func (*SSLCertListReq) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{7}
}

func (x *SSLCertListReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SSLCertListReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SSLCertListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SSLCertListReq) GetPagesize() uint32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

type SSLCertListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Pagesize uint32         `protobuf:"varint,2,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	Total    uint32         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data     []*SSLCertList `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SSLCertListRsp) Reset() {
	*x = SSLCertListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertListRsp) ProtoMessage() {}

func (x *SSLCertListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertListRsp.ProtoReflect.Descriptor instead.
func (*SSLCertListRsp) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{8}
}

func (x *SSLCertListRsp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SSLCertListRsp) GetPagesize() uint32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *SSLCertListRsp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SSLCertListRsp) GetData() []*SSLCertList {
	if x != nil {
		return x.Data
	}
	return nil
}

type SSLCertList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId       uint32              `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Title       string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Attrs       *SSLCertCreateAttrs `protobuf:"bytes,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Creator     uint32              `protobuf:"varint,5,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatorInfo *Creator            `protobuf:"bytes,6,opt,name=creatorInfo,proto3" json:"creatorInfo,omitempty"`
	CreatedAt   int64               `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SSLCertList) Reset() {
	*x = SSLCertList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertList) ProtoMessage() {}

func (x *SSLCertList) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertList.ProtoReflect.Descriptor instead.
func (*SSLCertList) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{9}
}

func (x *SSLCertList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSLCertList) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SSLCertList) GetAttrs() *SSLCertCreateAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *SSLCertList) GetCreator() uint32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *SSLCertList) GetCreatorInfo() *Creator {
	if x != nil {
		return x.CreatorInfo
	}
	return nil
}

func (x *SSLCertList) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SSLCertDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SslCertId    uint32 `protobuf:"varint,1,opt,name=ssl_cert_id,json=sslCertId,proto3" json:"ssl_cert_id,omitempty"`
	OrgId        uint32 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ConfirmToken string `protobuf:"bytes,3,opt,name=confirm_token,json=confirmToken,proto3" json:"confirm_token,omitempty"`
}

func (x *SSLCertDeleteReq) Reset() {
	*x = SSLCertDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertDeleteReq) ProtoMessage() {}

func (x *SSLCertDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertDeleteReq.ProtoReflect.Descriptor instead.
func (*SSLCertDeleteReq) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{10}
}

func (x *SSLCertDeleteReq) GetSslCertId() uint32 {
	if x != nil {
		return x.SslCertId
	}
	return 0
}

func (x *SSLCertDeleteReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertDeleteReq) GetConfirmToken() string {
	if x != nil {
		return x.ConfirmToken
	}
	return ""
}

type SSLCertProfileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SslCertId uint32 `protobuf:"varint,1,opt,name=ssl_cert_id,json=sslCertId,proto3" json:"ssl_cert_id,omitempty"`
	OrgId     uint32 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
}

func (x *SSLCertProfileReq) Reset() {
	*x = SSLCertProfileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertProfileReq) ProtoMessage() {}

func (x *SSLCertProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertProfileReq.ProtoReflect.Descriptor instead.
func (*SSLCertProfileReq) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{11}
}

func (x *SSLCertProfileReq) GetSslCertId() uint32 {
	if x != nil {
		return x.SslCertId
	}
	return 0
}

func (x *SSLCertProfileReq) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

type SSLCertProfileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert *SSLCertProfile `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *SSLCertProfileRsp) Reset() {
	*x = SSLCertProfileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertProfileRsp) ProtoMessage() {}

func (x *SSLCertProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertProfileRsp.ProtoReflect.Descriptor instead.
func (*SSLCertProfileRsp) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{12}
}

func (x *SSLCertProfileRsp) GetCert() *SSLCertProfile {
	if x != nil {
		return x.Cert
	}
	return nil
}

type SSLCertProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId       uint32              `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Title       string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Attrs       *SSLCertCreateAttrs `protobuf:"bytes,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Creator     uint32              `protobuf:"varint,5,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatorInfo *Creator            `protobuf:"bytes,6,opt,name=creatorInfo,proto3" json:"creatorInfo,omitempty"`
	CreatedAt   int64               `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SSLCertProfile) Reset() {
	*x = SSLCertProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLCertProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLCertProfile) ProtoMessage() {}

func (x *SSLCertProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ssl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLCertProfile.ProtoReflect.Descriptor instead.
func (*SSLCertProfile) Descriptor() ([]byte, []int) {
	return file_ssl_proto_rawDescGZIP(), []int{13}
}

func (x *SSLCertProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSLCertProfile) GetOrgId() uint32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *SSLCertProfile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SSLCertProfile) GetAttrs() *SSLCertCreateAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *SSLCertProfile) GetCreator() uint32 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *SSLCertProfile) GetCreatorInfo() *Creator {
	if x != nil {
		return x.CreatorInfo
	}
	return nil
}

func (x *SSLCertProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_ssl_proto protoreflect.FileDescriptor

var file_ssl_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x73, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x1a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x10, 0x53, 0x53, 0x4c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0x3f, 0x0a, 0x10, 0x53, 0x53, 0x4c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x53, 0x4c, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x63, 0x65, 0x72, 0x74, 0x73,
	0x22, 0x35, 0x0a, 0x0d, 0x53, 0x53, 0x4c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x71, 0x0a, 0x10, 0x53, 0x53, 0x4c, 0x43, 0x65,
	0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x22, 0x3d, 0x0a, 0x10, 0x53, 0x53,
	0x4c, 0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x29,
	0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x9c, 0x02, 0x0a, 0x0d, 0x53, 0x53,
	0x4c, 0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x74,
	0x74, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2e, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x74, 0x72, 0x73, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x12, 0x53, 0x53, 0x4c,
	0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22,
	0x87, 0x01, 0x0a, 0x0e, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x7f, 0x0a, 0x0e, 0x53, 0x53, 0x4c,
	0x43, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe8, 0x01, 0x0a, 0x0b, 0x53,
	0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x6e, 0x0a, 0x10, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x73, 0x6c,
	0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x73, 0x73, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x11, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x73,
	0x6c, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x73, 0x73, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49,
	0x64, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x53,
	0x4c, 0x43, 0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x22, 0xeb, 0x01, 0x0a, 0x0e, 0x53, 0x53, 0x4c, 0x43, 0x65, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x53, 0x4c, 0x43, 0x65,
	0x72, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52, 0x05, 0x61,
	0x74, 0x74, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ssl_proto_rawDescOnce sync.Once
	file_ssl_proto_rawDescData = file_ssl_proto_rawDesc
)

func file_ssl_proto_rawDescGZIP() []byte {
	file_ssl_proto_rawDescOnce.Do(func() {
		file_ssl_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssl_proto_rawDescData)
	})
	return file_ssl_proto_rawDescData
}

var file_ssl_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ssl_proto_goTypes = []interface{}{
	(*SSLSimpleListReq)(nil),   // 0: protoc.SSLSimpleListReq
	(*SSLSimpleListRsp)(nil),   // 1: protoc.SSLSimpleListRsp
	(*SSLSimpleList)(nil),      // 2: protoc.SSLSimpleList
	(*SSLCertCreateReq)(nil),   // 3: protoc.SSLCertCreateReq
	(*SSLCertCreateRsp)(nil),   // 4: protoc.SSLCertCreateRsp
	(*SSLCertCreate)(nil),      // 5: protoc.SSLCertCreate
	(*SSLCertCreateAttrs)(nil), // 6: protoc.SSLCertCreateAttrs
	(*SSLCertListReq)(nil),     // 7: protoc.SSLCertListReq
	(*SSLCertListRsp)(nil),     // 8: protoc.SSLCertListRsp
	(*SSLCertList)(nil),        // 9: protoc.SSLCertList
	(*SSLCertDeleteReq)(nil),   // 10: protoc.SSLCertDeleteReq
	(*SSLCertProfileReq)(nil),  // 11: protoc.SSLCertProfileReq
	(*SSLCertProfileRsp)(nil),  // 12: protoc.SSLCertProfileRsp
	(*SSLCertProfile)(nil),     // 13: protoc.SSLCertProfile
	(*Creator)(nil),            // 14: protoc.Creator
}
var file_ssl_proto_depIdxs = []int32{
	2,  // 0: protoc.SSLSimpleListRsp.certs:type_name -> protoc.SSLSimpleList
	5,  // 1: protoc.SSLCertCreateRsp.cert:type_name -> protoc.SSLCertCreate
	6,  // 2: protoc.SSLCertCreate.attrs:type_name -> protoc.SSLCertCreateAttrs
	14, // 3: protoc.SSLCertCreate.creatorInfo:type_name -> protoc.Creator
	9,  // 4: protoc.SSLCertListRsp.data:type_name -> protoc.SSLCertList
	6,  // 5: protoc.SSLCertList.attrs:type_name -> protoc.SSLCertCreateAttrs
	14, // 6: protoc.SSLCertList.creatorInfo:type_name -> protoc.Creator
	13, // 7: protoc.SSLCertProfileRsp.cert:type_name -> protoc.SSLCertProfile
	6,  // 8: protoc.SSLCertProfile.attrs:type_name -> protoc.SSLCertCreateAttrs
	14, // 9: protoc.SSLCertProfile.creatorInfo:type_name -> protoc.Creator
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ssl_proto_init() }
func file_ssl_proto_init() {
	if File_ssl_proto != nil {
		return
	}
	file_creator_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ssl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLSimpleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLSimpleListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLSimpleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertCreateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertCreateAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertProfileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertProfileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSLCertProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ssl_proto_goTypes,
		DependencyIndexes: file_ssl_proto_depIdxs,
		MessageInfos:      file_ssl_proto_msgTypes,
	}.Build()
	File_ssl_proto = out.File
	file_ssl_proto_rawDesc = nil
	file_ssl_proto_goTypes = nil
	file_ssl_proto_depIdxs = nil
}
