// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: usersshkey.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建私人秘钥请求
type UserPersonalSshKeyCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Remark string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *UserPersonalSshKeyCreateReq) Reset() {
	*x = UserPersonalSshKeyCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPersonalSshKeyCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPersonalSshKeyCreateReq) ProtoMessage() {}

func (x *UserPersonalSshKeyCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPersonalSshKeyCreateReq.ProtoReflect.Descriptor instead.
func (*UserPersonalSshKeyCreateReq) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{0}
}

func (x *UserPersonalSshKeyCreateReq) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *UserPersonalSshKeyCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建私人秘钥返回值
type UserPersonalSshKeyCreateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *UserPersonalSshKeyCreate `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UserPersonalSshKeyCreateRsp) Reset() {
	*x = UserPersonalSshKeyCreateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPersonalSshKeyCreateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPersonalSshKeyCreateRsp) ProtoMessage() {}

func (x *UserPersonalSshKeyCreateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPersonalSshKeyCreateRsp.ProtoReflect.Descriptor instead.
func (*UserPersonalSshKeyCreateRsp) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{1}
}

func (x *UserPersonalSshKeyCreateRsp) GetKey() *UserPersonalSshKeyCreate {
	if x != nil {
		return x.Key
	}
	return nil
}

type UserPersonalSshKeyCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid         uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Pubkey      string `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Remark      string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Fingerprint string `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	CreatedAt   int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *UserPersonalSshKeyCreate) Reset() {
	*x = UserPersonalSshKeyCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPersonalSshKeyCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPersonalSshKeyCreate) ProtoMessage() {}

func (x *UserPersonalSshKeyCreate) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPersonalSshKeyCreate.ProtoReflect.Descriptor instead.
func (*UserPersonalSshKeyCreate) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{2}
}

func (x *UserPersonalSshKeyCreate) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPersonalSshKeyCreate) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserPersonalSshKeyCreate) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *UserPersonalSshKeyCreate) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserPersonalSshKeyCreate) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *UserPersonalSshKeyCreate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UserPlatformSshPublicKeyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sshkey *UserPlatformSshPublicKey `protobuf:"bytes,1,opt,name=sshkey,proto3" json:"sshkey,omitempty"`
}

func (x *UserPlatformSshPublicKeyRsp) Reset() {
	*x = UserPlatformSshPublicKeyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPlatformSshPublicKeyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPlatformSshPublicKeyRsp) ProtoMessage() {}

func (x *UserPlatformSshPublicKeyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPlatformSshPublicKeyRsp.ProtoReflect.Descriptor instead.
func (*UserPlatformSshPublicKeyRsp) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{3}
}

func (x *UserPlatformSshPublicKeyRsp) GetSshkey() *UserPlatformSshPublicKey {
	if x != nil {
		return x.Sshkey
	}
	return nil
}

type UserPlatformSshPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pubkey      string                               `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	GenerateAt  int64                                `protobuf:"varint,2,opt,name=generate_at,json=generateAt,proto3" json:"generate_at,omitempty"`
	Fingerprint *UserPlatformSshPublicKeyFingerprint `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (x *UserPlatformSshPublicKey) Reset() {
	*x = UserPlatformSshPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPlatformSshPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPlatformSshPublicKey) ProtoMessage() {}

func (x *UserPlatformSshPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPlatformSshPublicKey.ProtoReflect.Descriptor instead.
func (*UserPlatformSshPublicKey) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{4}
}

func (x *UserPlatformSshPublicKey) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *UserPlatformSshPublicKey) GetGenerateAt() int64 {
	if x != nil {
		return x.GenerateAt
	}
	return 0
}

func (x *UserPlatformSshPublicKey) GetFingerprint() *UserPlatformSshPublicKeyFingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

type UserPlatformSshPublicKeyFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha256 string `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *UserPlatformSshPublicKeyFingerprint) Reset() {
	*x = UserPlatformSshPublicKeyFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersshkey_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPlatformSshPublicKeyFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPlatformSshPublicKeyFingerprint) ProtoMessage() {}

func (x *UserPlatformSshPublicKeyFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_usersshkey_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPlatformSshPublicKeyFingerprint.ProtoReflect.Descriptor instead.
func (*UserPlatformSshPublicKeyFingerprint) Descriptor() ([]byte, []int) {
	return file_usersshkey_proto_rawDescGZIP(), []int{5}
}

func (x *UserPlatformSshPublicKeyFingerprint) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_usersshkey_proto protoreflect.FileDescriptor

var file_usersshkey_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x73, 0x73, 0x68, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x4d, 0x0a, 0x1b, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x51, 0x0a, 0x1b, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x73, 0x68, 0x4b, 0x65,
	0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xad, 0x01, 0x0a,
	0x18, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x73, 0x68,
	0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x66,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x57, 0x0a, 0x1b,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x06, 0x73,
	0x73, 0x68, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x53, 0x73, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x73,
	0x73, 0x68, 0x6b, 0x65, 0x79, 0x22, 0xa2, 0x01, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x4d, 0x0a, 0x0b, 0x66,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x66,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x23, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_usersshkey_proto_rawDescOnce sync.Once
	file_usersshkey_proto_rawDescData = file_usersshkey_proto_rawDesc
)

func file_usersshkey_proto_rawDescGZIP() []byte {
	file_usersshkey_proto_rawDescOnce.Do(func() {
		file_usersshkey_proto_rawDescData = protoimpl.X.CompressGZIP(file_usersshkey_proto_rawDescData)
	})
	return file_usersshkey_proto_rawDescData
}

var file_usersshkey_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_usersshkey_proto_goTypes = []interface{}{
	(*UserPersonalSshKeyCreateReq)(nil),         // 0: protoc.UserPersonalSshKeyCreateReq
	(*UserPersonalSshKeyCreateRsp)(nil),         // 1: protoc.UserPersonalSshKeyCreateRsp
	(*UserPersonalSshKeyCreate)(nil),            // 2: protoc.UserPersonalSshKeyCreate
	(*UserPlatformSshPublicKeyRsp)(nil),         // 3: protoc.UserPlatformSshPublicKeyRsp
	(*UserPlatformSshPublicKey)(nil),            // 4: protoc.UserPlatformSshPublicKey
	(*UserPlatformSshPublicKeyFingerprint)(nil), // 5: protoc.UserPlatformSshPublicKeyFingerprint
}
var file_usersshkey_proto_depIdxs = []int32{
	2, // 0: protoc.UserPersonalSshKeyCreateRsp.key:type_name -> protoc.UserPersonalSshKeyCreate
	4, // 1: protoc.UserPlatformSshPublicKeyRsp.sshkey:type_name -> protoc.UserPlatformSshPublicKey
	5, // 2: protoc.UserPlatformSshPublicKey.fingerprint:type_name -> protoc.UserPlatformSshPublicKeyFingerprint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_usersshkey_proto_init() }
func file_usersshkey_proto_init() {
	if File_usersshkey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usersshkey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPersonalSshKeyCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersshkey_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPersonalSshKeyCreateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersshkey_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPersonalSshKeyCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersshkey_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPlatformSshPublicKeyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersshkey_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPlatformSshPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersshkey_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPlatformSshPublicKeyFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usersshkey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usersshkey_proto_goTypes,
		DependencyIndexes: file_usersshkey_proto_depIdxs,
		MessageInfos:      file_usersshkey_proto_msgTypes,
	}.Build()
	File_usersshkey_proto = out.File
	file_usersshkey_proto_rawDesc = nil
	file_usersshkey_proto_goTypes = nil
	file_usersshkey_proto_depIdxs = nil
}
