syntax = "proto3";

package protoc;

option go_package = "/protoc;protoc";

import "cluster.proto";
import "env.proto";

message InstanceSimpleReq{
  uint32 org_id=1;
  uint32 group_id=2;
  uint32 project_id=3;
  uint32 env_id=4;
  uint32 cluster_id=5;
}

message InstanceSimpleRsp{
  repeated InstanceSimple pods=1;
}

message InstanceSimple{
  uint32 id=1;
  uint32 org_id=2;
  uint32 group_id=3;
  uint32 project_id=4;
  uint32 env_id=5;
  uint32 cluster_id=6;
  string group=7;
  Cluster  cluster=8;
  Env env=9;
}

message InstanceProfileReq{
  uint32 org_id=1;
  uint32 group_id=2;
  uint32 project_id=3;
  uint32 pod_id=4;
}

message InstanceProfileRsp{

}


