syntax = "proto3";

package protoc;

option go_package = "/protoc;protoc";

import "creator.proto";

message Orgs{
  repeated Organization orgs = 1;
}

message Organization{
  uint32 id = 1; // 组织id
  uint32 type = 2; // 类型：0-个人；1-公司
  string type_s = 3; // 类型中文
  string title = 4; // 组织名称
  string alias = 5; // 组织标识
  string logo = 6; // LOGO
  string desc = 7; // 组织描述
  uint32 role = 8; // 角色
  string role_s = 9; // 角色中文
  uint32 status = 10; // 状态
  string status_s = 11; // 状态中文
}

enum OrgROLE{
  ROLE_Normal = 0;
  ROLE_MANAGER = 1;//管理员
  ROLE_PM = 2;//产品经理
  ROLE_DEV = 3;//研发
  ROLE_TESTER = 4;//测试
  ROLE_OPS = 5;//运维
  ROLE_DIRECTOR = 9;//负责人
}
enum OrgAUTH{
  AUTH_NO = 0;//未认证
  AUTH_COMPANY = 1;//企业认证
  AUTH_PERSONAL = 2; //个人认证
}

enum OrgTYPE{
  TYPE_PERSONAL = 0;//个人
  TYPE_COMPANY = 1;//公司
}

enum OrgSTATUS{
  STATUS_IN_DISSOLUTION = 0;//解散中
  STATUS_NORMAL = 1;//正常
}

message OrgProfileRsp{
  OrgProfile org = 1;
}
// 组织详情
message OrgProfile{
  uint32 id = 1; // 组织id
  OrgAUTH id_auth = 2;
  string title = 3;
  OrgTYPE  type = 4;
  OrgSTATUS status = 5;
  OrgROLE  role = 6;
  string logo = 7;
  bool is_admin_org = 8;// 是否是组织所有者
  string desc = 9;
  uint32 creator = 10;
  Creator  creator_info = 11;
  int64 created_at = 12;
}